version: '3.7'
services:
  postgres:
    container_name: task-command-db
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
